api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "shipping-filter"
type = "function"
uid = "dc8215f2-a7ab-213d-e7eb-69074f08cd6bb8c2c299"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
